//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retention
    {
        public int retentionId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<bool> cancelStatus { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public Nullable<int> totalCancelAmount { get; set; }
        public Nullable<bool> updateStatus { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> totalUpdateAmount { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
