//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public string transactionType { get; set; }
        public string transactionStatus { get; set; }
        public Nullable<int> transactionAmount { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
